sudo: required
services:
    - docker

before_install:
    - docker build -t tangolf88/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true tangolf88/react-test npm test

after_success:
    - docker build -t tangolf88/multi-client ./client
    - docker build -t tangolf88/multi-nginx ./nginx
    - docker build -t tangolf88/multi-server ./server
    - docker build -t tangolf88/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push the to docker hub
    - docker push tangolf88/multi-client
    - docker push tangolf88/multi-nginx
    - docker push tangolf88/multi-server
    - docker push tangolf88/multi-worker

deploy:
    provider: elasticbeanstalk
    region: eu-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-2-259629792391
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id:
        secure: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
